# Generated by Django 5.1.7 on 2025-03-09 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaEvaluate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('voice_input', models.FileField(blank=True, null=True, upload_to='voice_inputs/')),
                ('document', models.FileField(blank=True, null=True, upload_to='idea_documents/')),
                ('feasibility_score', models.FloatField(blank=True, null=True)),
                ('future_predictions', models.TextField(blank=True, null=True)),
                ('risk_analysis', models.TextField(blank=True, null=True)),
                ('uvp_analysis', models.TextField(blank=True, null=True)),
                ('evaluation_score', models.IntegerField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('improvement_suggestions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea_evaluate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='evaluator.ideaevaluate')),
            ],
        ),
    ]
